---
title: "p8105_hw2_bg2715"
output: github_document
---
```{r}
library(tidyverse)
library(readxl)
```


Problem 1

Read and clean the Mr. Trash Wheel sheet.
```{r}
Tr_Wh_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2(80).xlsx", sheet = 1) %>%
  
  janitor::clean_names() %>%

  #omitting non-data entries  
  select(-x15, -x16, -x17) %>%
  
  #omitting rows that do not include dumpster-specific data
  drop_na(date) %>%
  
  mutate(sports_balls = round(sports_balls))
  
```

Read and clean precipitation data for 2018 and 2019.
```{r}
Prec_18_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2(80).xlsx", range = "A2:B14", sheet = 7) %>%
  
  janitor::clean_names() %>% 
  
  mutate(year = 2018)


Prec_19_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2(80).xlsx", range = "A2:B14", sheet = 6) %>%
  
  janitor::clean_names() %>%
  
  mutate(year = 2019) 
  
Prec_18_19_df = 
  #combining precipitation datasets
  bind_rows(Prec_18_df,Prec_19_df) %>% 
  
  relocate(year) %>%
  
  #converting month to a character variable 
  mutate(month = month.name[month]) 
```

A paragraph about these data.
```{r}
#the number of observations
nrow(Tr_Wh_df)

nrow(Prec_18_19_df)

#examples of key variables
names(Tr_Wh_df)

names(Prec_18_19_df)

#the total precipitation in 2018
subset(Prec_18_19_df, year == 2018) %>%
  
  pull(total) %>%
  
  sum()

#the median number of sports balls in a dumpster in 2019
subset(Tr_Wh_df, year == 2019) %>%
  
  pull(sports_balls) %>%
  
  median()
```

Problem 2

clean the data in pols-month
```{r}
pols_month_df = 
  read.csv("./data/pols-month.csv") %>%
  
  janitor::clean_names() %>%
  
  separate(mon, c("year", "month", "day")) %>%
  
  #replace month number with month name
  mutate(month = as.numeric(month)) %>%
  
  mutate(month = month.name[month]) %>%
  
  #create a president variable taking values gop and  dem, and remove prez_dem and prez_gop
  pivot_longer(
    c(prez_dem, prez_gop),
    names_to = "president",
    names_prefix = "prez_"
  ) %>%
  
  filter(value == 1) %>%
  
  select(-value) %>%
  
  #remove the day variable
  select(-day)
```

clean the data in snp.csv
```{r}
snp_df = 
  read.csv("./data/snp.csv") %>%
  
  mutate(
    lubridate::mdy(date)
  ) %>%
  
  select(-date) %>%
  
  separate("lubridate::mdy(date)", c('year', 'month', 'day')) %>%
  
  #replace month number with month name
  mutate(month = as.numeric(month)) %>%
  
  mutate(month = month.name[month]) %>%
  
  select(-day) %>%
  
  #organize so that year and month are the leading columns
  relocate(year, month) %>%
  
  #arrange according to year and month
  arrange(year, month)
```



