p8105\_hw2\_bg2715
================

``` r
library(tidyverse)
```

    ## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --

    ## v ggplot2 3.3.5     v purrr   0.3.4
    ## v tibble  3.1.5     v dplyr   1.0.7
    ## v tidyr   1.1.4     v stringr 1.4.0
    ## v readr   2.0.2     v forcats 0.5.1

    ## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

Problem 1

Read and clean the Mr. Trash Wheel sheet.

``` r
Tr_Wh_df = 
  readxl::read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2(80).xlsx", sheet = 1) %>%
  
  janitor::clean_names() %>%

  #omitting non-data entries  
  select(-x15, -x16, -x17) %>%
  
  #omitting rows that do not include dumpster-specific data
  drop_na(date) %>%
  
  mutate(sports_balls = round(sports_balls))
```

    ## New names:
    ## * `` -> ...15
    ## * `` -> ...16
    ## * `` -> ...17

Read and clean precipitation data for 2018 and 2019.

``` r
Prec_18_df = 
  readxl::read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2(80).xlsx", range = "A2:B14", sheet = 7) %>%
  
  janitor::clean_names() %>% 
  
  mutate(year = 2018)


Prec_19_df = 
  readxl::read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2(80).xlsx", range = "A2:B14", sheet = 6) %>%
  
  janitor::clean_names() %>%
  
  mutate(year = 2019) 
  
Prec_18_19_df = 
  #combining precipitation datasets
  bind_rows(Prec_18_df,Prec_19_df) %>% 
  
  relocate(year) %>%
  
  #converting month to a character variable 
  mutate(month = month.name[month]) 
```

A paragraph about these data:

``` r
#the number of observations
nrow(Tr_Wh_df)
```

    ## [1] 453

``` r
nrow(Prec_18_19_df)
```

    ## [1] 24

``` r
#examples of key variables
names(Tr_Wh_df)
```

    ##  [1] "dumpster"           "month"              "year"              
    ##  [4] "date"               "weight_tons"        "volume_cubic_yards"
    ##  [7] "plastic_bottles"    "polystyrene"        "cigarette_butts"   
    ## [10] "glass_bottles"      "grocery_bags"       "chip_bags"         
    ## [13] "sports_balls"       "homes_powered"

``` r
names(Prec_18_19_df)
```

    ## [1] "year"  "month" "total"

``` r
#the total precipitation in 2018
subset(Prec_18_19_df, year == 2018) %>%
  
  pull(total) %>%
  
  sum()
```

    ## [1] 70.33

``` r
#the median number of sports balls in a dumpster in 2019
subset(Tr_Wh_df, year == 2019) %>%
  
  pull(sports_balls) %>%
  
  median()
```

    ## [1] 9

The Mr. Traswheel dataset has 453 rows and 14 columns. Key variables
include “weight\_tons”, “cigarette\_butts”, “glass\_bottles”, and
“homes\_powered.” The median number of sports balls in 2019 is 9. The
combined precipitation data has 24 rows and 3 columns. Key variables
include “year”, “month” and “total”. The total precipitation in 2018 is
70.33.

Problem 2

clean the data in pols-month

``` r
pols_month_df = 
  read.csv("./data/pols-month.csv") %>%
  
  janitor::clean_names() %>%
  
  separate(mon, c("year", "month", "day")) %>%
  
  #replace month number with month name
  mutate(month = as.numeric(month)) %>%
  
  mutate(month = month.abb[month]) %>%
  
  #create a president variable taking values gop and  dem, and remove prez_dem and prez_gop
  pivot_longer(
    c(prez_dem, prez_gop),
    names_to = "president",
    names_prefix = "prez_"
  ) %>%
  
  filter(value == 1) %>%
  
  select(-value) %>%
  
  #remove the day variable
  select(-day)
```

clean the data in snp.csv

``` r
snp_df = 
  read.csv("./data/snp.csv") %>%
  
  janitor::clean_names() %>%
  
  mutate(
    lubridate::mdy(date)
  ) %>%
  
  select(-date) %>%
  
  separate("lubridate::mdy(date)", c('year', 'month', 'day')) %>%
  
  #replace month number with month name
  mutate(month = as.numeric(month)) %>%
  
  mutate(month = month.abb[month]) %>%
  
  select(-day) %>%
  
  #organize so that year and month are the leading columns
  relocate(year, month) %>%
  
  #arrange according to year and month
  arrange(year, month)
```

tidy the unemployment data so that it can be merged with the previous
datasets.

``` r
unemp_df = 
  read.csv("./data/unemployment.csv") %>%
  
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "perc_unemp"
  ) %>% 
  
  rename(year = Year) %>%
  
  mutate(year = as.character(year))
```

Join the datasets

``` r
pols_snp = 
  inner_join(pols_month_df, snp_df, by = c("year" = "year", "month" = "month"))

pols_snp_unemp =
  inner_join(pols_snp, unemp_df, by = c("year" = "year", "month" = "month"))
```

A paragraph about these data:

``` r
dim(pols_snp_unemp)
```

    ## [1] 553  11

``` r
range(pull(pols_snp_unemp, year))
```

    ## [1] "1969" "2015"

``` r
names(pols_snp_unemp)
```

    ##  [1] "year"       "month"      "gov_gop"    "sen_gop"    "rep_gop"   
    ##  [6] "gov_dem"    "sen_dem"    "rep_dem"    "president"  "close"     
    ## [11] "perc_unemp"

The pols\_month\_df contains 817 observations of 9 variables related to
the number of national politicians who are democratic or republican at
any given time. The snp\_df contains 787 observations of 3 variables
related to Standard & Poor’s stock market index (S&P), often used as a
representative measure of stock market as a whole. The unemp\_df
contains 816 observations of 3 variables. Merging these three datasets
by year and month in an inner joint, we get the joint data.The joint
data has 553 columns and 11 rows. Key variables include “president”,
“close” and “perc\_unemp”. The range of years is 1969 to 2015.

Problem 3

Load and tidy the data.

``` r
baby_names_df = read_csv("./data/Popular_Baby_Names.csv") %>% 
  
  janitor::clean_names() %>% 
  
  distinct(year_of_birth, ethnicity, childs_first_name, .keep_all = TRUE)
```

    ## Rows: 19418 Columns: 6

    ## -- Column specification --------------------------------------------------------
    ## Delimiter: ","
    ## chr (3): Gender, Ethnicity, Child's First Name
    ## dbl (3): Year of Birth, Count, Rank

    ## 
    ## i Use `spec()` to retrieve the full column specification for this data.
    ## i Specify the column types or set `show_col_types = FALSE` to quiet this message.

table showing the rank in popularity of the name “Olivia” as a female
baby name over time.

``` r
olivia_df = pivot_wider(
  baby_names_df,
  names_from = year_of_birth,
  values_from = rank
) %>% 
  
  filter(childs_first_name == "Olivia")
```

table showing the most popular name among male children over time

``` r
male_df = filter(
  baby_names_df,
  rank == "1",
  gender == "MALE"
) %>% 
  
  pivot_wider(
  names_from = year_of_birth,
  values_from = childs_first_name
) 
```

scatter plot

``` r
scat_plot_df = filter(
  baby_names_df,
  gender == "MALE",
  ethnicity == "WHITE NON HISPANIC",
  year_of_birth == "2016"
)

plot_MW2 = ggplot(scat_plot_df, aes(x = rank, y = count, color = childs_first_name)) + geom_point() + xlab("The rank in popularity of that name") + ylab("The number of children with a name") + theme(legend.position = "none") 

#ggsave("plot_MW2.png")
```
